[features]
seeds = false
[programs.localnet]
anchor_basics = "Dq6U4UQs8cKCup4LzhFPU8AvEpHEKm7byAZYy6PK7Yai"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/threedevx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
